# torrnado (torrnado.dev) theme, generated by theme-switcher from the active
# palette. Linked as ~/.config/torrnado/themes/current.toml; config.toml
# selects it with theme = "current".
background  = "{{ background }}"
foreground  = "{{ foreground }}"
muted       = "{{ muted }}"
accent      = "{{ accent }}"
success     = "{{ green }}"
warning     = "{{ yellow }}"
error       = "{{ red }}"
# torrnado draws pane outlines in this; its built-ins use muted, since a
# surface shade disappears into the background.
border      = "{{ muted }}"
selected_bg = "{{ selection }}"
selected_fg = "{{ foreground }}"
