#!/usr/bin/env bash
set -e

# import pretty_print
source scripts/common

# Oh my zsh installation
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  pretty_print "${green}Installing oh-my-zsh...${neutral}"
  curl -L http://install.ohmyz.sh | sh
else
  pretty_print "${yellow}oh-my-zsh is already installed, skipping ...${neutral}"
fi

# Homebrew installation
if ! command -v brew &>/dev/null; then
  pretty_print "${green}Installing Homebrew, an OSX package manager, follow the instructions...${neutral}"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  pretty_print "${yellow}You already have Homebrew installed, skipping ...${neutral}"
fi

pretty_print "${green}Updating brew formulas${neutral}"
brew update

brew bundle --file install/Brewfile
brew bundle --file install/Caskfile

# Installing vscode extensions
for ext in $(cat install/Codefile)
do
  pretty_print "Installing vscode extension: $ext"
  code --install-extension $ext --force
done

# install rust
curl https://sh.rustup.rs -sSf | bash -s -- -y

# Install terraform
tfenv install $TERRAFORM_VERSION
tfenv use $TERRAFORM_VERSION

pretty_print "${green}Copying configs to .configs directory${neutral}"
mkdir -p ~/.config
cp -R .config/* ~/.config

pretty_print "${green}Installing fonts${neutral}"
mkdir -p /Users/$USER/Library/Fonts
cp fonts/*.ttf /Users/$USER/Library/Fonts
cp fonts/*.otf /Users/$USER/Library/Fonts

pretty_print "${green}Installing icons${neutral}"
cp icons/Alacritty.icns /Applications/Alacritty.app/Contents/Resources/alacritty.icns

if [ ! -d $HOME/.config/alacritty/themes ]; then
  mkdir -p ~/.config/alacritty/themes
  git clone --depth=1 https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
fi

# https://github.com/alacritty/alacritty/releases/tag/v0.11.0
defaults write -g AppleFontSmoothing -int 2

pretty_print "${green}Configuring plugins for zsh${neutral}"
[ ! -d ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions ] && \
  git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

[ ! -d ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting ] && \
  git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

pretty_print "${green}Changing zshrc config${neutral}"
cp .config/zsh/.zshrc /Users/$USER/.zshrc

pretty_print "Configuring vscode"
cp .config/code/settings.json /Users/$USER/Library/Application\ Support/Code/User/settings.json

if [ ! -d $HOME/.config/vifm/colors ];
then
  mkdir -p ~/.config/vifm/colors
  git clone https://github.com/vifm/vifm-colors ~/.config/vifm/colors
fi

# Install tmux plugin manager
if [ ! -d $HOME/.config/tmux/plugins ];
then
  mkdir -p $HOME/.config/tmux/plugins/tpm
  git clone https://github.com/tmux-plugins/tpm $HOME/.config/tmux/plugins/tpm
fi

# Install python if not installed
[ ! -d $HOME/.pyenv/versions/$PYTHON_VERSION ] && pyenv install $PYTHON_VERSION

pretty_print "${green}We are done!...everything looks good!${neutral}"
